[package]
name = "htb_2023_leaking_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = "1.22.0"
itertools = "0.11.0"
rayon = "1.8.0"
hex = "0.4.3"
indicatif = { version = "0.17.7", features = ["rayon"] }
